name = "kumo-auth"
main = "src/index.ts"
compatibility_date = "2024-10-22"

compatibility_flags = [ "nodejs_compat" ]

[vars]
JWT_SECRET = "${JWT_SECRET}"
JWT_EXPIRE_IN = "${JWT_EXPIRE_IN}"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "kumo-auth"
database_id = "${D1_DATABASE_ID}"

# [ai]
# binding = "AI"

# head_sampling_rate set to 1 is log all, 0 is no log at all.
[observability]
enabled = true
head_sampling_rate = 1